arxiv: 
  path: /home/jth264/.cache/kagglehub/datasets/Cornell-University/arxiv/versions/235/arxiv-metadata-oai-snapshot.json
  
ncl: 
  path: /home/share/data/ncl_json

ncl_llm_summary: 
  path: /home/wenjieluu1130/RAG/data/test/108.jsonl

history: 
  path: data/history

root: 
  path: /home/share/data
