arxiv: 
  path: /home/jth264/.cache/kagglehub/datasets/Cornell-University/arxiv/versions/235/arxiv-metadata-oai-snapshot.json
  
ncl: 
  path: /home/share/data/ncl_json

history: 
  path: data/history

root: 
  path: /share/data
